@echo off
ren %CD%\data\RIYADH\inputs\ICONIS_KERNEL_PARAMETER_DESCRIPTION.xml Default_ICONIS_KERNEL_PARAMETER_DESCRIPTION.xml
copy %CD%\RIYADH_TRANSFORMER\output\ICONIS_KERNEL_PARAMETER_DESCRIPTION.xml %CD%\data\RIYADH\inputs
pause